apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-deployment
spec:
  selector:
      matchLabels:
        app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
        - name: skaffold-container
          image: withnic/skaffold-example
          ports:
          - containerPort: 8080