apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: withnic/skaffold-example
    context: .
  local:
    push: false
test:
  - image: withnic/skaffold-example
    structureTests:
      - ./test/*
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: test
    test:
      - image: withnic/skaffold-example
        structureTests:
          - ./test/profile_structure_test.yaml